debug: true
spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/quartz_db
    username: postgres
    password: postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  quartz:
    job-store-type: jdbc
  
    
server:
  port: 8088
  
 